import asyncio
import aiohttp
import io
from hydrogram import Client, filters, enums
from hydrogram.types import InlineKeyboardMarkup, InlineKeyboardButton
from info import HF_TOKEN

# ==========================================
# 🎨 HIGH QUALITY IMAGE GENERATION (SDXL 1.0)
# Using Hugging Face Inference API
# ==========================================

# Using Stable Diffusion XL Base 1.0 model for top tier quality
API_URL = "https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-xl-base-1.0"
headers = {"Authorization": f"Bearer {HF_TOKEN}"}

async def query_hg(prompt):
    async with aiohttp.ClientSession() as session:
        try:
            async with session.post(API_URL, headers=headers, json={"inputs": prompt}, timeout=60) as response:
                if response.status == 200:
                    return await response.read()
                elif response.status == 503:
                    # Model is loading, wait a bit
                    await asyncio.sleep(5)
                    return await query_hg(prompt) # Retry once
                else:
                    error_data = await response.text()
                    print(f"HG API Error: {error_data}")
                    return None
        except Exception as e:
             print(f"Connection Error: {e}")
             return None

@Client.on_message(filters.command(["draw", "imagine", "img"]))
async def draw_image(client, message):
    # 1. Check Token
    if not HF_TOKEN:
        return await message.reply("❌ **Error:** Hugging Face Token (`HF_TOKEN`) is missing in Config.")

    # 2. Check Input
    if len(message.command) < 2:
        return await message.reply(
            "🎨 **SDXL High-Quality Generator**\n\n"
            "Usage: `/draw <prompt>`\n"
            "Example: `/draw a futuristic city at sunset, cinematic lighting, 8k`"
        )

    # 3. Get Prompt & Notify
    prompt = message.text.split(None, 1)[1]
    status_msg = await message.reply(f"🎨 **Generating High-Quality Art...**\n`{prompt}`\n\n_This may take 10-20 seconds._")
    await client.send_chat_action(message.chat.id, enums.ChatAction.UPLOAD_PHOTO)

    try:
        # 4. Call API (Async)
        image_bytes = await query_hg(prompt)

        if not image_bytes:
            return await status_msg.edit("❌ **Error:** Failed to generate image. API might be busy or prompt is NSFW.")

        # 5. Convert bytes to virtual file
        image_io = io.BytesIO(image_bytes)
        image_io.name = "generated_image.jpg"

        # 6. Send Photo
        await client.send_photo(
            chat_id=message.chat.id,
            photo=image_io,
            caption=f"✨ **Prompt:** `{prompt}`\n🎨 **Model:** SDXL 1.0\n🤖 **Generated by:** @{client.me.username}",
            reply_markup=InlineKeyboardMarkup([
                [InlineKeyboardButton("🗑 Delete", callback_data="close_data")]
            ])
        )
        await status_msg.delete()

    except Exception as e:
        await status_msg.edit(f"❌ **Error Occurred:** `{str(e)}`")

